name: qdl
summary: qdl Qualcomm Download tool
description: |
  This tool communicates with USB devices of id 05c6:9008 to upload a flash
  loader and use this to flash images.

base: core24

grade: stable
confinement: strict
adopt-info: qdl
license: BSD-3-Clause

platforms:
  arm64:
  amd64:
  riscv64:

environment:
  LD_LIBRARY_PATH: "$SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}"

plugs:
  home:
    read: all

apps:
  qdl:
    command: usr/bin/qdl
    plugs:
      - raw-usb
      - home
      - network-observe
      - adb-support
  ramdump:
    command: usr/bin/qdl-ramdump
    plugs:
      - raw-usb
      - home
      - network-observe

parts:
  qdl:
    plugin: nil
    source: https://github.com/linux-msm/qdl.git
    source-type: git
    source-branch: master
    stage-packages:
      - libxml2
      - libusb-1.0-0
    override-build: |
      make
      install -D -m 755 qdl ${SNAPCRAFT_PART_INSTALL}/usr/bin/qdl
      install -D -m 755 qdl-ramdump ${SNAPCRAFT_PART_INSTALL}/usr/bin/qdl-ramdump
      craftctl set version="$(git describe --tag | cut -c 2-)"

build-packages:
  - cmake
  - pkgconf
  - libusb-1.0-0-dev
  - libxml2-dev
